export const FETCH_RECOMMENDED_RECIPES = 'FETCH_RECOMMENDED_RECIPES';
export const FETCH_RECOMMENDED_RECIPES_SUCCESS = 'FETCH_RECOMMENDED_RECIPES_SUCCESS';
export const FETCH_RECOMMENDED_RECIPES_FAILURE = 'FETCH_RECOMMENDED_RECIPES_FAILURE';

export const FAVORITE_RECIPE = 'FAVORITE_RECIPE';
export const UNFAVORITE_RECIPE = 'UNFAVORITE_RECIPE';
