export const FETCH_RECOMMENDED_RECIPES = 'FETCH_RECOMMENDED_RECIPES';
export const FETCH_RECOMMENDED_RECIPES_SUCCESS = 'FETCH_RECOMMENDED_RECIPES_SUCCESS';
export const FETCH_RECOMMENDED_RECIPES_FAILURE = 'FETCH_RECOMMENDED_RECIPES_FAILURE';

export const REFRESH_RECOMMENDED_RECIPES = 'REFRESH_RECOMMENDED_RECIPES';
export const REFRESH_RECOMMENDED_RECIPES_SUCCESS = 'REFRESH_RECOMMENDED_RECIPES_SUCCESS';
export const REFRESH_RECOMMENDED_RECIPES_FAILURE = 'REFRESH_RECOMMENDED_RECIPES_FAILURE';

export const FETCH_MORE_RECOMMENDED_RECIPES_SUCCESS = 'FETCH_MORE_RECOMMENDED_RECIPES_SUCCESS';

export const GET_FAVORITED_SUCCESS = 'GET_FAVORITED_SUCCESS';

export const FETCH_FAVORITED_RECIPES = 'FETCH_FAVORITED_RECIPES';
export const FETCH_FAVORITED_RECIPES_SUCCESS = 'FETCH_FAVORITED_RECIPES_SUCCESS';
export const FETCH_FAVORITED_RECIPES_FAILURE = 'FETCH_FAVORITED_RECIPES_FAILURE';

export const REFRESH_FAVORITED__RECIPES = 'REFRESH_FAVORITED_RECIPES';
export const REFRESH_FAVORITED_RECIPES_SUCCESS = 'REFRESH_FAVORITED_RECIPES_SUCCESS';
export const REFRESH_FAVORITED_RECIPES_FAILURE = 'REFRESH_FAVORITED_RECIPES_FAILURE';

export const FETCH_MORE_FAVORITED_RECIPES_SUCCESS = 'FETCH_MORE_FAVORITED_RECIPES_SUCCESS';

export const FAVORITE_RECIPE = 'FAVORITE_RECIPE';
export const UNFAVORITE_RECIPE = 'UNFAVORITE_RECIPE';
