export const FETCH_RECIPES = 'FETCH_RECIPES';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';

export const REFRESH_RECIPES = 'REFRESH_RECIPES';
export const REFRESH_RECIPES_SUCCESS = 'REFRESH_RECIPES_SUCCESS';
export const REFRESH_RECIPES_FAILURE = 'REFRESH_RECIPES_FAILURE';

export const FETCH_MORE_RECIPES_SUCCESS = 'FETCH_MORE_RECIPES_SUCCESS';

export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS';
export const FAVORITE_RECIPE = 'FAVORITE_RECIPE';
export const UNFAVORITE_RECIPE = 'UNFAVORITE_RECIPE';
